//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XafDelta.Delivery.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XafDelta.Delivery.Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close transport {0} .
        /// </summary>
        internal static string CloseTransport {
            get {
                return ResourceManager.GetString("CloseTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} deletion error: {1}.
        /// </summary>
        internal static string DeleteError {
            get {
                return ResourceManager.GetString("DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} deleted.
        /// </summary>
        internal static string DeleteOk {
            get {
                return ResourceManager.GetString("DeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error: {0}.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file {0} ....
        /// </summary>
        internal static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading finished.
        /// </summary>
        internal static string DownloadFinished {
            get {
                return ResourceManager.GetString("DownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading started.
        /// </summary>
        internal static string DownloadStarted {
            get {
                return ResourceManager.GetString("DownloadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download using transport {0}.
        /// </summary>
        internal static string DownloadUsing {
            get {
                return ResourceManager.GetString("DownloadUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) found for download.
        /// </summary>
        internal static string FilesForDownload {
            get {
                return ResourceManager.GetString("FilesForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} messages found for upload.
        /// </summary>
        internal static string FoundForUpload {
            get {
                return ResourceManager.GetString("FoundForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open transport {0} .
        /// </summary>
        internal static string OpenTransport {
            get {
                return ResourceManager.GetString("OpenTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transport(s) found for download.
        /// </summary>
        internal static string TransportFound {
            get {
                return ResourceManager.GetString("TransportFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload error: {0}.
        /// </summary>
        internal static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading finished.
        /// </summary>
        internal static string UploadFinished {
            get {
                return ResourceManager.GetString("UploadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file {0} ....
        /// </summary>
        internal static string UploadingFile {
            get {
                return ResourceManager.GetString("UploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading started.
        /// </summary>
        internal static string UploadStarted {
            get {
                return ResourceManager.GetString("UploadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport for uploading is not found. Please append at list one transport module to application..
        /// </summary>
        internal static string UploadTransportNotFound {
            get {
                return ResourceManager.GetString("UploadTransportNotFound", resourceCulture);
            }
        }
    }
}
