//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XafDelta.Delivery.WcfTransport.WcfTransportClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfTransportClient.ITransportService")]
    public interface ITransportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportService/GetFileNames", ReplyAction="http://tempuri.org/ITransportService/GetFileNamesResponse")]
        string[] GetFileNames(string mask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportService/UploadFile", ReplyAction="http://tempuri.org/ITransportService/UploadFileResponse")]
        void UploadFile(string fileName, byte[] fileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportService/DownloadFile", ReplyAction="http://tempuri.org/ITransportService/DownloadFileResponse")]
        byte[] DownloadFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportService/DeleteFile", ReplyAction="http://tempuri.org/ITransportService/DeleteFileResponse")]
        void DeleteFile(string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransportServiceChannel : XafDelta.Delivery.WcfTransport.WcfTransportClient.ITransportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportServiceClient : System.ServiceModel.ClientBase<XafDelta.Delivery.WcfTransport.WcfTransportClient.ITransportService>, XafDelta.Delivery.WcfTransport.WcfTransportClient.ITransportService {
        
        public TransportServiceClient() {
        }
        
        public TransportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetFileNames(string mask) {
            return base.Channel.GetFileNames(mask);
        }
        
        public void UploadFile(string fileName, byte[] fileData) {
            base.Channel.UploadFile(fileName, fileData);
        }
        
        public byte[] DownloadFile(string fileName) {
            return base.Channel.DownloadFile(fileName);
        }
        
        public void DeleteFile(string fileName) {
            base.Channel.DeleteFile(fileName);
        }
    }
}
