//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XafDelta.Delivery.WcfTransport.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XafDelta.Delivery.WcfTransport.Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF client is not opened.
        /// </summary>
        internal static string ClientIsNotOpened {
            get {
                return ResourceManager.GetString("ClientIsNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF client is opened succesfully..
        /// </summary>
        internal static string ClientOpened {
            get {
                return ResourceManager.GetString("ClientOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading error for file {0}: {1}.
        /// </summary>
        internal static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded OK.
        /// </summary>
        internal static string DownloadOk {
            get {
                return ResourceManager.GetString("DownloadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File listing error: {1}.
        /// </summary>
        internal static string FileListingError {
            get {
                return ResourceManager.GetString("FileListingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File listing OK.
        /// </summary>
        internal static string FileListingOk {
            get {
                return ResourceManager.GetString("FileListingOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading error for file {0}: {1}.
        /// </summary>
        internal static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded OK.
        /// </summary>
        internal static string UploadOk {
            get {
                return ResourceManager.GetString("UploadOk", resourceCulture);
            }
        }
    }
}
