//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XafDelta.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XafDelta.Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aborted.
        /// </summary>
        internal static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building packages.
        /// </summary>
        internal static string BuildingPackages {
            get {
                return ResourceManager.GetString("BuildingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building snapshot for {0} replication node.
        /// </summary>
        internal static string BuildingSnapshotForNode {
            get {
                return ResourceManager.GetString("BuildingSnapshotForNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build object maps.
        /// </summary>
        internal static string BuildObjectMaps {
            get {
                return ResourceManager.GetString("BuildObjectMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create snapshot for disabled node..
        /// </summary>
        internal static string CantCreateSnapshotForDisabled {
            get {
                return ResourceManager.GetString("CantCreateSnapshotForDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete current replication node.
        /// </summary>
        internal static string CantDeleteNode {
            get {
                return ResourceManager.GetString("CantDeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} collision detected for package record {1}. Resolved to {2}..
        /// </summary>
        internal static string CollisionDetected {
            get {
                return ResourceManager.GetString("CollisionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication collision {0} error: .
        /// </summary>
        internal static string CollisionError {
            get {
                return ResourceManager.GetString("CollisionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commiting changes.
        /// </summary>
        internal static string CommitChanges {
            get {
                return ResourceManager.GetString("CommitChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting is aborted..
        /// </summary>
        internal static string ExportAborted {
            get {
                return ResourceManager.GetString("ExportAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export is finished.
        /// </summary>
        internal static string ExportFinished {
            get {
                return ResourceManager.GetString("ExportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting file {0} ....
        /// </summary>
        internal static string ExportingFile {
            get {
                return ResourceManager.GetString("ExportingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is empty.
        /// </summary>
        internal static string FileNameIsEmpty {
            get {
                return ResourceManager.GetString("FileNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files selected for export.
        /// </summary>
        internal static string FilesSelectedForExport {
            get {
                return ResourceManager.GetString("FilesSelectedForExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files selected for import.
        /// </summary>
        internal static string FilesSelectedForImport {
            get {
                return ResourceManager.GetString("FilesSelectedForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing is aborted..
        /// </summary>
        internal static string ImportAborted {
            get {
                return ResourceManager.GetString("ImportAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import finished.
        /// </summary>
        internal static string ImportFinished {
            get {
                return ResourceManager.GetString("ImportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing file {0} ....
        /// </summary>
        internal static string ImportingFile {
            get {
                return ResourceManager.GetString("ImportingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file extension for file {0}. File skipped..
        /// </summary>
        internal static string ImportInvalidFileExtension {
            get {
                return ResourceManager.GetString("ImportInvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package {0} is already exists in replication storage. File skipped..
        /// </summary>
        internal static string ImportPackageExists {
            get {
                return ResourceManager.GetString("ImportPackageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket {0} is already exists in replication storage. File skipped..
        /// </summary>
        internal static string ImportTicketExists {
            get {
                return ResourceManager.GetString("ImportTicketExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package data: .
        /// </summary>
        internal static string InvalidPackageData {
            get {
                return ResourceManager.GetString("InvalidPackageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package file name.
        /// </summary>
        internal static string InvalidPackageFileName {
            get {
                return ResourceManager.GetString("InvalidPackageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package Id for package {0}. Actual {1}, expected {2}.
        /// </summary>
        internal static string InvalidPackageId {
            get {
                return ResourceManager.GetString("InvalidPackageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {2}: actual {0} expected {1}.
        /// </summary>
        internal static string InvalidPackageProp {
            get {
                return ResourceManager.GetString("InvalidPackageProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading aborted by user.
        /// </summary>
        internal static string LoadingAborted {
            get {
                return ResourceManager.GetString("LoadingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package loading is {0}.
        /// </summary>
        internal static string LoadingIs {
            get {
                return ResourceManager.GetString("LoadingIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages loading is finished.
        /// </summary>
        internal static string LoadingIsFinished {
            get {
                return ResourceManager.GetString("LoadingIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading package {0}.
        /// </summary>
        internal static string LoadingPackage {
            get {
                return ResourceManager.GetString("LoadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages loading started.
        /// </summary>
        internal static string LoadingStarted {
            get {
                return ResourceManager.GetString("LoadingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is reserved for broadcast packages and shouldn&apos;t be used as NodeId.
        /// </summary>
        internal static string NodeIdAllNodes {
            get {
                return ResourceManager.GetString("NodeIdAllNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NodeId contains invalid characters: &apos;{0}&apos;.
        /// </summary>
        internal static string NodeIdInvalidChars {
            get {
                return ResourceManager.GetString("NodeIdInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source objects found for snapshot. Snapshot is not created..
        /// </summary>
        internal static string NoObjectsFoundForSnapshot {
            get {
                return ResourceManager.GetString("NoObjectsFoundForSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newObject is not implements ISessionProvider.
        /// </summary>
        internal static string NotSessionProvider {
            get {
                return ResourceManager.GetString("NotSessionProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} objects found in snapshot.
        /// </summary>
        internal static string ObjectsFoundInSnapshot {
            get {
                return ResourceManager.GetString("ObjectsFoundInSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created package {0}.
        /// </summary>
        internal static string PackageCreated {
            get {
                return ResourceManager.GetString("PackageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package data is empty for package {0}..
        /// </summary>
        internal static string PackageDataIsEmpty {
            get {
                return ResourceManager.GetString("PackageDataIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package loading is failed with error {0}.
        /// </summary>
        internal static string PackageLoadError {
            get {
                return ResourceManager.GetString("PackageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package {0} loading is completed successfully.
        /// </summary>
        internal static string PackageLoadingCompleted {
            get {
                return ResourceManager.GetString("PackageLoadingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package {0} loading is failed.
        /// </summary>
        internal static string PackageLoadingIsFailed {
            get {
                return ResourceManager.GetString("PackageLoadingIsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package {0} is rejected.
        /// </summary>
        internal static string PackageRejected {
            get {
                return ResourceManager.GetString("PackageRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol package saving is failed with error {0}.
        /// </summary>
        internal static string PackageSaveFailed {
            get {
                return ResourceManager.GetString("PackageSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol packages saving is {0}.
        /// </summary>
        internal static string PackageSavingIs {
            get {
                return ResourceManager.GetString("PackageSavingIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} packages selected for loading.
        /// </summary>
        internal static string PackagesSelectedForLoading {
            get {
                return ResourceManager.GetString("PackagesSelectedForLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication.
        /// </summary>
        internal static string Replication {
            get {
                return ResourceManager.GetString("Replication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving data for protocol session {0}.
        /// </summary>
        internal static string SavingSessionData {
            get {
                return ResourceManager.GetString("SavingSessionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} packages selected for loading.
        /// </summary>
        internal static string SelectedForLoading {
            get {
                return ResourceManager.GetString("SelectedForLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender node {0} is not found for package {1}. Anonymous package loading are not allowed..
        /// </summary>
        internal static string SenderNodeIsNotFound {
            get {
                return ResourceManager.GetString("SenderNodeIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package session {0} was already loaded.
        /// </summary>
        internal static string SessionAlreadyLoaded {
            get {
                return ResourceManager.GetString("SessionAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data for protocol session {0} is saved.
        /// </summary>
        internal static string SessionDataSaved {
            get {
                return ResourceManager.GetString("SessionDataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should save target replication node before create snapshot..
        /// </summary>
        internal static string ShouldSaveTargetNode {
            get {
                return ResourceManager.GetString("ShouldSaveTargetNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot building is {0}.
        /// </summary>
        internal static string SnapshotBuildingIs {
            get {
                return ResourceManager.GetString("SnapshotBuildingIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot building is failed with error {0}.
        /// </summary>
        internal static string SnapshotFailed {
            get {
                return ResourceManager.GetString("SnapshotFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot loading is {0}.
        /// </summary>
        internal static string SnapshotLoadingIs {
            get {
                return ResourceManager.GetString("SnapshotLoadingIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot loading is failed with error {0}.
        /// </summary>
        internal static string SnapshotLoadingIsFailed {
            get {
                return ResourceManager.GetString("SnapshotLoadingIsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot object &quot;{0}&quot;.
        /// </summary>
        internal static string SnapshotObject {
            get {
                return ResourceManager.GetString("SnapshotObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot object &quot;{0}&quot; property &quot;{1}&quot;.
        /// </summary>
        internal static string SnapshotProperty {
            get {
                return ResourceManager.GetString("SnapshotProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} source objects found for class {1}.
        /// </summary>
        internal static string SourceObjectsFoundForClass {
            get {
                return ResourceManager.GetString("SourceObjectsFoundForClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object already exists in application database.
        /// </summary>
        internal static string TargetObjectExists {
            get {
                return ResourceManager.GetString("TargetObjectExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object is not found in application database.
        /// </summary>
        internal static string TargetObjectNotFound {
            get {
                return ResourceManager.GetString("TargetObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0} objects is snapshoted.
        /// </summary>
        internal static string TotalObjectsSnapshoted {
            get {
                return ResourceManager.GetString("TotalObjectsSnapshoted", resourceCulture);
            }
        }
    }
}
